# Generated by Django 5.2.16 on 2026-08-12 04:23
from django.db import migrations, models
from pgvector.django import (
    HalfVectorField,
    HnswIndex,
    VectorExtension,
)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="SemanticCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_hash",
                    models.CharField(
                        max_length=64,
                        help_text="SHA-256 hash for exact match verification",
                    ),
                ),
                (
                    "input_embedding",
                    HalfVectorField(
                        dimensions=3072,
                        help_text="Embedding for semantic search",
                    ),
                ),
                (
                    "response",
                    models.JSONField(
                        help_text="JSON response from the AI model for reuse",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("quiz", "Question Generation"),
                            ("adaptive_practice", "Adaptive Question Generation"),
                            ("grading", "AI Grading"),
                            ("knowledge_graph", "Map Generation"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        default="1",
                        max_length=30,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_used_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=[
                            "input_hash",
                            "purpose",
                            "model_name",
                            "prompt_version",
                        ],
                        name="unique_semantic_cache_input",
                    ),
                ],
                "indexes": [
                    HnswIndex(
                        name="semantic_cache_embedding_hnsw",
                        fields=["input_embedding"],
                        m=16,
                        ef_construction=64,
                        opclasses=["halfvec_cosine_ops"],
                    ),
                ],
            },
        ),
    ]
