# Generated by Django 5.2.16 on 2026-08-12 04:23
from django.db import migrations, models
from pgvector.django import (
    HalfVectorField,
    HnswIndex,
    VectorExtension,
)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="SemanticCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_hash",
                    models.CharField(
                        max_length=64,
                        help_text="完全一致確認用のSHA-256ハッシュ",
                    ),
                ),
                (
                    "input_embedding",
                    HalfVectorField(
                        dimensions=3072,
                        help_text="意味検索に使用する入力文のEmbedding",
                    ),
                ),
                (
                    "response",
                    models.JSONField(
                        help_text="再利用するAIのJSON応答",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("quiz", "問題生成"),
                            ("adaptive_practice", "適応型問題生成"),
                            ("grading", "AI採点"),
                            ("knowledge_graph", "マップ生成"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        default="1",
                        max_length=30,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_used_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=[
                            "input_hash",
                            "purpose",
                            "model_name",
                            "prompt_version",
                        ],
                        name="unique_semantic_cache_input",
                    ),
                ],
                "indexes": [
                    HnswIndex(
                        name="semantic_cache_embedding_hnsw",
                        fields=["input_embedding"],
                        m=16,
                        ef_construction=64,
                        opclasses=["halfvec_cosine_ops"],
                    ),
                ],
            },
        ),
    ]
    