# Generated by Django 5.2.16 on 2026-08-12 16:28

import django.core.validators
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_enable_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(db_index=True, max_length=100)),
                ('content', models.TextField()),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('feedback', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=3072)),
            ],
            options={
                'verbose_name': 'reference sample',
                'verbose_name_plural': 'reference samples',
                'ordering': ['exercise_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SemanticAICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(db_index=True, max_length=50)),
                ('original_text', models.TextField()),
                ('text_embedding', pgvector.django.vector.VectorField(dimensions=3072)),
                ('ai_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'semantic AI cache',
                'verbose_name_plural': 'semantic AI caches',
                'ordering': ['-created_at'],
            },
        ),
    ]
