# Generated by Django 5.2.16 on 2026-08-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, through='notes.NoteTag', to='notes.tag'),
        ),
    ]
