# Generated by Django 6.1 on 2026-08-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='folders', to='notes.tag'),
        ),
        migrations.AlterField(
            model_name='note',
            name='template_type',
            field=models.CharField(blank=True, default='blank', max_length=50),
        ),
    ]
