# Generated by Django 6.1 on 2026-08-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_folder_tags_alter_note_template_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='tags',
        ),
    ]
