# Generated by Django 6.1 on 2026-08-13 03:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('notes', '0004_remove_folder_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='AIのnodes[].idに対応するノート内の識別子', max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(help_text='教師が標準採点した比較用の模範回答')),
                ('human_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rubric_details', models.JSONField(blank=True, default=dict, help_text='教師による項目別の点数と採点理由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='quizattempt',
            name='quiz_attempt_score_between_0_and_100',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='generation_type',
        ),
        migrations.AddField(
            model_name='attempt',
            name='rubric_details',
            field=models.JSONField(blank=True, default=dict, help_text='AIが返した項目別の点数・根拠・要点分解'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddField(
            model_name='mapnode',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_nodes', to='notes.note'),
        ),
        migrations.AddField(
            model_name='mapedge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='learning.mapnode'),
        ),
        migrations.AddField(
            model_name='mapedge',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='learning.mapnode'),
        ),
        migrations.AddField(
            model_name='referencesample',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_samples', to='learning.exercise'),
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='score',
        ),
        migrations.AddConstraint(
            model_name='mapnode',
            constraint=models.UniqueConstraint(fields=('note', 'key'), name='unique_map_node_key_per_note'),
        ),
        migrations.AddConstraint(
            model_name='mapedge',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'label'), name='unique_map_edge'),
        ),
        migrations.AddConstraint(
            model_name='referencesample',
            constraint=models.CheckConstraint(condition=models.Q(('human_score__gte', 0), ('human_score__lte', 100)), name='reference_sample_score_between_0_and_100'),
        ),
    ]
