# Generated by Django 5.2.16 on 2026-08-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_mapedge_mapnode_referencesample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='reasoning',
            field=models.TextField(blank=True, default='', help_text='ユーザーが入力した、問題を解くための論理ステップ'),
        ),
    ]
