# Generated by Django 5.2.16 on 2026-08-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_attempt_quiz_attempt_alter_exercise_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='reasoning',
            field=models.TextField(blank=True, default='', help_text='Logical steps taken by the user to solve the problem'),
        ),
    ]
