# Generated by Django 5.2.16 on 2026-08-17 04:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_attempt_reasoning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'ユーザー'), ('model', 'AI Tutor')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TutorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ready_for_grading', models.BooleanField(default=False)),
                ('compiled_final_answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),

        migrations.AddField(
            model_name='tutorsession',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_sessions', to='learning.exercise'),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='quiz_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_sessions', to='learning.quizattempt'),
        ),
        migrations.AddField(
            model_name='tutorsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutormessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='learning.tutorsession'),
        ),
        migrations.DeleteModel(
            name='MapEdge',
        ),
        migrations.DeleteModel(
            name='MapNode',
        ),
        migrations.DeleteModel(
            name='ReferenceSample',
        ),
    ]
