# Generated by Django 5.2.16 on 2026-08-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizschedule',
            name='priority',
            field=models.IntegerField(choices=[(1, 'P1 - Highest Priority'), (2, 'P2 - High Priority'), (3, 'P3 - Medium Priority'), (4, 'P4 - Low Priority'), (5, 'P5 - Lowest Priority')], default=1),
        ),
        migrations.AddField(
            model_name='quizschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizschedule',
            name='weekly_days',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quizschedule',
            name='question_count',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='quizschedule',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
