# Generated by Django 5.2.16 on 2026-08-14 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_folder_tags'),
        ('scheduler', '0002_quizschedule_end_time_quizschedule_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizschedule',
            name='created_at',
        ),
        migrations.AddField(
            model_name='quizschedule',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='notes.folder'),
        ),
        migrations.AddField(
            model_name='quizschedule',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='notes.note'),
        ),
    ]
