# Generated by Django 5.2.16 on 2026-08-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_remove_quizschedule_created_at_quizschedule_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
