# Generated by Django 5.2.16 on 2026-08-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizschedule',
            name='weekly_days',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quizschedule',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizschedule',
            name='priority',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='quizschedule',
            name='target_resource',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='quizschedule',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizschedule',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('adaptive', 'Adaptive')], default='adaptive', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizschedule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('specific', 'Specific Date')], default='daily', max_length=20),
        ),
    ]
