# Generated by Django 5.2.16 on 2026-08-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_quizschedule_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizschedule',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizschedule',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('adaptive', 'Adaptive')], default='adaptive', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizschedule',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('specific', 'Specific Date')], default='daily', max_length=20),
        ),
    ]
