# Generated by Django 5.2.16 on 2026-08-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_quizschedule_specific_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizschedule',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Dễ'), ('medium', 'Trung bình'), ('hard', 'Khó'), ('adaptive', 'Tự động')], default='adaptive', max_length=20),
        ),
    ]
