# Generated by Django 5.2.16 on 2026-08-16 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_quizschedule_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizschedule',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='quizschedule',
            name='question_count',
        ),
    ]
